let allProxies = [];
let filteredProxies = [];

const proxyGrid = document.getElementById('proxyGrid');
const loading = document.getElementById('loading');
const error = document.getElementById('error');
const proxyCountEl = document.getElementById('proxyCount');
const lastUpdateEl = document.getElementById('lastUpdate');
const searchInput = document.getElementById('searchInput');
const searchBtn = document.getElementById('searchBtn');
const refreshBtn = document.getElementById('refreshBtn');
const filterBtns = document.querySelectorAll('.filter-btn[data-filter]');

// Fetch proxies from the JSON file (generated by GitHub Actions)
async function fetchProxies() {
    loading.style.display = 'block';
    error.style.display = 'none';
    proxyGrid.innerHTML = '';

    try {
        const response = await fetch('proxies.json?t=' + Date.now());
        if (!response.ok) throw new Error('Failed to fetch');
        
        const data = await response.json();
        allProxies = data.proxies;
        filteredProxies = [...allProxies];
        
        proxyCountEl.textContent = allProxies.length;
        lastUpdateEl.textContent = new Date(data.lastUpdate).toLocaleTimeString();
        
        displayProxies(filteredProxies);
        loading.style.display = 'none';
    } catch (err) {
        console.error('Error fetching proxies:', err);
        loading.style.display = 'none';
        error.style.display = 'block';
    }
}

// Display proxies in grid
function displayProxies(proxies) {
    proxyGrid.innerHTML = '';
    
    if (proxies.length === 0) {
        proxyGrid.innerHTML = '<div class="glass-card" style="grid-column: 1/-1; text-align: center;">No proxies found matching your criteria.</div>';
        return;
    }

    proxies.forEach((proxy, index) => {
        const card = document.createElement('div');
        card.className = 'proxy-card';
        card.style.animationDelay = `${index * 0.05}s`;
        
        const telegramLink = `https://t.me/proxy?server=${proxy.ip}&port=${proxy.port}`;
        
        card.innerHTML = `
            <div class="proxy-header">
                <span class="proxy-icon">🌐</span>
                <span class="proxy-status">✓ Active</span>
            </div>
            <div class="proxy-info">
                <div class="proxy-ip">${proxy.ip}</div>
                <div class="proxy-port">Port: ${proxy.port}</div>
            </div>
            <a href="${telegramLink}" class="telegram-link" target="_blank" rel="noopener noreferrer">
                📱 Add to Telegram
            </a>
        `;
        
        proxyGrid.appendChild(card);
    });
}

// Search functionality
function searchProxies() {
    const searchTerm = searchInput.value.toLowerCase().trim();
    
    if (searchTerm === '') {
        filteredProxies = [...allProxies];
    } else {
        filteredProxies = allProxies.filter(proxy => 
            proxy.ip.includes(searchTerm) || 
            proxy.port.toString().includes(searchTerm)
        );
    }
    
    displayProxies(filteredProxies);
    proxyCountEl.textContent = filteredProxies.length;
}

// Filter functionality
filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        filterBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        
        const filter = btn.dataset.filter;
        
        if (filter === 'all') {
            filteredProxies = [...allProxies];
        } else if (filter === 'fast') {
            // Filter by common fast proxy ports or implement your own logic
            filteredProxies = allProxies.filter(proxy => 
                parseInt(proxy.port) < 10000
            );
        }
        
        displayProxies(filteredProxies);
        proxyCountEl.textContent = filteredProxies.length;
    });
});

// Event listeners
searchBtn.addEventListener('click', searchProxies);
searchInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') searchProxies();
});
refreshBtn.addEventListener('click', fetchProxies);

// Copy to clipboard functionality
function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
        showToast('✓ Copied to clipboard!');
    });
}

function showToast(message) {
    const toast = document.createElement('div');
    toast.style.cssText = `
        position: fixed;
        bottom: 2rem;
        right: 2rem;
        background: rgba(0, 0, 0, 0.8);
        color: #fff;
        padding: 1rem 2rem;
        border-radius: 12px;
        z-index: 1000;
        animation: slideIn 0.3s ease;
    `;
    toast.textContent = message;
    document.body.appendChild(toast);
    
    setTimeout(() => {
        toast.remove();
    }, 3000);
}

// Initial load
fetchProxies();

// Auto-refresh every 5 minutes
setInterval(fetchProxies, 5 * 60 * 1000);